version: '3'

services:
  db:
    image: mysql:5
    restart: on-failure
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
